config/routes.rb
WhiteList::Application.routes.draw do
  
  get '/domains/refresh' => 'domains#refresh_all'
  
  resources :domains do
    resources :ips
    get 'refresh'
  end

  devise_for :users
  
  resources :actions do
    get 'perform'
  end
  
  root :to => 'actions#index'
  devise_for :users, :path => "/", :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'sign_up' }
  

end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  # GET /actions
  # GET /actions.json
  def index
    @actions = Action.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @actions }
    end
  end

  # GET /actions/1
  # GET /actions/1.json
  def show
    @action = Action.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @action }
    end
  end

  # GET /actions/new
  # GET /actions/new.json
  def new
    @action = Action.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @action }
    end
  end

  # GET /actions/1/edit
  def edit
    @action = Action.find(params[:id])
  end

  # POST /actions
  # POST /actions.json
  def create
    @action = Action.new(params[:command])

    respond_to do |format|
      if @action.save
        format.html { redirect_to @action, notice: 'Action was successfully created.' }
        format.json { render json: @action, status: :created, location: @action }
      else
        format.html { render action: "new" }
        format.json { render json: @action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /actions/1
  # PUT /actions/1.json
  def update
    @action = Action.find(params[:id])

    respond_to do |format|
      if @action.update_attributes(params[:command])
        format.html { redirect_to @action, notice: 'Action was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actions/1
  # DELETE /actions/1.json
  def destroy
    @action = Action.find(params[:id])
    @action.destroy

    respond_to do |format|
      format.html { redirect_to actions_url }
      format.json { head :no_content }
    end
  end
  
  def perform    
    action = Action.find params[:action_id]
    action.perform
    
    redirect_to domains_path
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/views/actions/_form.html.erb
<%= form_for @action, :as => :command, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :command, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :command, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                actions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/actions/edit.html.erb
<%- model_class = @action.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/actions/index.html.erb
<%- model_class = Action.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:command) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @actions.each do |action| %>
      <tr>
        <td><%= link_to action.id, action_path(action) %></td>
        <td><%= action.name %></td>
        <td><%= action.description %></td>
        <td><%= action.command %></td>
        <td><%=l action.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_action_path(action), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      action_path(action),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= "#{SSH_USER}:#{SSH_PASSWORD}@#{SSH_HOST}"%>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_action_path,
            :class => 'btn btn-primary' %>

app/views/actions/new.html.erb
<%- model_class = @action.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/actions/show.html.erb
<%- model_class = @action.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @action.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @action.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:command) %>:</strong></dt>
  <dd><%= @action.command %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              actions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_action_path(@action), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              action_path(@action),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>