config/routes.rb
WhiteList::Application.routes.draw do
  
  get '/domains/refresh' => 'domains#refresh_all'
  
  resources :domains do
    resources :ips
    get 'refresh'
  end

  devise_for :users
  
  resources :actions do
    get 'perform'
  end
  
  root :to => 'actions#index'
  devise_for :users, :path => "/", :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'sign_up' }
  

end

app/models/domain.rb
require 'socket'

class Domain < ActiveRecord::Base
  attr_accessible :address, :name
  
  has_many :ips
  
  def self.parse_domain(domain)
    domain.gsub(/http:\/\//, '').gsub(/\//, '')
  end
  
  def lookup
    addrs = Socket.getaddrinfo(self.address, "http", nil, :STREAM)
  end
  
  def refresh
    puts "*" * 80
    begin
      addrs = lookup
      refresh_infos(addrs)
    rescue
      refresh
    end
  end
  
  def refresh_infos(addrs)
    self.ips.each do |ip|
      ip.destroy
    end
            
    addrs.each do |addr|
      self.ips << Ip.create(:ip => addr[2], :port => addr[1])
    end
    self
  end
end

app/controllers/domains_controller.rb
require 'socket'

class DomainsController < ApplicationController
  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @domains }
    end
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
    @domain = Domain.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @domain }
    end
  end

  # GET /domains/new
  # GET /domains/new.json
  def new
    @domain = Domain.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @domain }
    end
  end

  # GET /domains/1/edit
  def edit
    @domain = Domain.find(params[:id])
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(:name => params[:domain][:name], :address => Domain.parse_domain(params[:domain][:address]))
    @domain.refresh
    
    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render json: @domain, status: :created, location: @domain }
      else
        format.html { render action: "new" }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /domains/1
  # PUT /domains/1.json
  def update
    @domain = Domain.find(params[:id])

    respond_to do |format|
      if @domain.update_attributes(params[:domain])
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy

    respond_to do |format|
      format.html { redirect_to domains_url }
      format.json { head :no_content }
    end
  end
  
  def refresh
    @domain = Domain.find_by_id(params[:domain_id]).refresh
    @domain = Domain.find @domain.id
    redirect_to @domain
  end
  
  def refresh_all
    @domain = Domain.all.each do |d|
      d.refresh
    end
    redirect_to domains_path
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= form_for @domain, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                domains_path, :class => 'btn' %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<%- model_class = @domain.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/domains/index.html.erb
<%- model_class = Domain.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= link_to domain.id, domain_path(domain) %></td>
        <td><%= domain.name %></td>
        <td><%= domain.address %></td>
        <td><%=l domain.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_domain_path(domain), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      domain_path(domain),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_domain_path,
            :class => 'btn btn-primary' %>
            
<%= link_to 'refresh all',
            domains_refresh_path,
            :class => 'btn' %>

<% Action.all.each do |action|%>
  <%= link_to action.name, action_perform_path(action.id), :class => 'btn'%>
<% end%>

app/views/domains/new.html.erb
<%- model_class = @domain.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/domains/show.html.erb
<%- model_class = @domain.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @domain.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @domain.address %></dd>
</dl>

<h2>IPs</h2>
<ul class='ips'>
  <% @domain.ips.each do |ip|%>
    <li><%= ip.ip.to_s + ":" + ip.port.to_s%></li>
  <% end%>
</ul>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              domains_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_domain_path(@domain), :class => 'btn' %>
              
  <%= link_to 'Refresh DNS', domain_refresh_path(@domain.id), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              domain_path(@domain),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>