config/routes.rb
WhiteList::Application.routes.draw do
  
  get '/domains/refresh' => 'domains#refresh_all'
  
  resources :domains do
    resources :ips
    get 'refresh'
  end

  devise_for :users
  
  resources :actions do
    get 'perform'
  end
  
  root :to => 'actions#index'
  devise_for :users, :path => "/", :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'sign_up' }
  

end

app/models/ip.rb
require 'socket'

class Ip < ActiveRecord::Base
  attr_accessible :domain_id, :ip, :port
  
  belongs_to :domain
  
  
end

app/controllers/ips_controller.rb
class IpsController < ApplicationController
  # GET /ips
  # GET /ips.json
  def index
    @ips = Ip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ips }
    end
  end

  # GET /ips/1
  # GET /ips/1.json
  def show
    @ip = Ip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ip }
    end
  end

  # GET /ips/new
  # GET /ips/new.json
  def new
    @ip = Ip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ip }
    end
  end

  # GET /ips/1/edit
  def edit
    @ip = Ip.find(params[:id])
  end

  # POST /ips
  # POST /ips.json
  def create
    @ip = Ip.new(params[:ip])

    respond_to do |format|
      if @ip.save
        format.html { redirect_to @ip, notice: 'Ip was successfully created.' }
        format.json { render json: @ip, status: :created, location: @ip }
      else
        format.html { render action: "new" }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ips/1
  # PUT /ips/1.json
  def update
    @ip = Ip.find(params[:id])

    respond_to do |format|
      if @ip.update_attributes(params[:ip])
        format.html { redirect_to @ip, notice: 'Ip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ips/1
  # DELETE /ips/1.json
  def destroy
    @ip = Ip.find(params[:id])
    @ip.destroy

    respond_to do |format|
      format.html { redirect_to ips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ips_helper.rb
module IpsHelper
end

app/views/ips/_form.html.erb
<%= form_for @ip, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                ips_path, :class => 'btn' %>
  </div>
<% end %>

app/views/ips/edit.html.erb
<%- model_class = @ip.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/ips/index.html.erb
<%- model_class = Ip.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ips.each do |ip| %>
      <tr>
        <td><%= link_to ip.id, ip_path(ip) %></td>
        <td><%=l ip.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ip_path(ip), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      ip_path(ip),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ip_path,
            :class => 'btn btn-primary' %>

app/views/ips/new.html.erb
<%- model_class = @ip.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/ips/show.html.erb
<%- model_class = @ip.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              ips_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ip_path(@ip), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ip_path(@ip),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>